# Generated by Django 4.1.1 on 2022-09-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_addr', models.CharField(max_length=50)),
                ('c_email', models.CharField(max_length=50)),
                ('c_phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('gst_id', models.AutoField(primary_key=True, serialize=False)),
                ('igst', models.IntegerField()),
                ('category_gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_addr', models.CharField(max_length=50)),
                ('vgst_no', models.CharField(max_length=50)),
                ('vphone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('product_stock', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('reorder_level', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.offer')),
                ('gst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.gst')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCustomer',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_cost', models.FloatField()),
                ('tax_amount', models.IntegerField()),
                ('discount', models.FloatField()),
                ('netamount', models.FloatField()),
                ('invoice_date', models.DateTimeField()),
                ('customer_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.customer')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.invoicecustomer')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.product')),
            ],
        ),
    ]
