# Generated by Django 4.1.1 on 2022-09-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('v_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_datetime', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('vendorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('vquantity', models.FloatField()),
                ('vprice', models.FloatField()),
                ('vdatetime', models.DateTimeField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.product')),
                ('vendorinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.vendorinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('bs_id', models.AutoField(primary_key=True, serialize=False)),
                ('light_bill', models.FloatField()),
                ('emp_salary', models.FloatField()),
                ('monthly_rent', models.FloatField()),
                ('miscellaneous', models.FloatField()),
                ('bs_datetime', models.DateTimeField()),
                ('bs_cinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.invoicecustomer')),
                ('bs_vendor_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust.vendorinvoice')),
            ],
        ),
    ]
